### ISSUE TITLE
Inactive maintainer

### ISSUE THREAD

**Issue by aparcar** [byrnereese/mkdocs-bootstrap4#6]
Hi, this theme is great, however comes with a few bugs (fixed via PRs). @byrnereese would you mind merging those PRs adding others as contributors so they can continue maintaining the theme?

**Comment by byrnereese** [comment]
I merged the PRs submitted and pushed the update. I will admit, I was a bad boy and did not test them before publishing them.

**Comment by aparcar** [comment]
That"s the spirit! Thanks for merging
